#!/usr/bin/env python3
"""Render PROGRAM_STATUS.md deterministically from the program registries."""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

from validate_program import (
    DEFAULT_EXPERIMENTS,
    DEFAULT_REGISTRY,
    DEFAULT_THEORY_MAP,
    DEFAULT_THEORY_REGISTRY,
    EXPECTED_REPOSITORIES,
    LIFECYCLE_STAGES,
    load_json,
    validate,
    validate_theory,
)

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "PROGRAM_STATUS.md"


def _cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def render(registry: dict, experiments: dict) -> str:
    errors = validate(registry, experiments)
    theory = load_json(DEFAULT_THEORY_REGISTRY)
    theory_map_text = DEFAULT_THEORY_MAP.read_text(encoding="utf-8")
    errors.extend(validate_theory(theory, registry, theory_map_text))
    if errors:
        raise ValueError("cannot render invalid registry: " + "; ".join(errors))

    repositories = registry["repositories"]
    stages = Counter(repo["lifecycle_stage"] for repo in repositories)
    states = Counter(repo["program_state"] for repo in repositories)
    experiment_by_id = {item["id"]: item for item in experiments["experiments"]}
    current_concepts = [
        concept
        for concept in theory["concepts"]
        if concept["current_repository"] is not None
    ]
    lines = [
        "# Opsle program status",
        "",
        "<!-- Generated by tools/render_program_status.py from program/registry.json, "
        "program/experiments.json, program/theory-registry.json, and "
        "program/THEORY_MAP.md. -->",
        "",
        f"**Coverage: {len(repositories)}/{len(EXPECTED_REPOSITORIES)} expected repositories; duplicates: 0.**",
        "",
        f"Last verified: `{registry['last_verified_at']}`. HEADs are the verified default-branch revisions, not an assumption about later changes.",
        "",
        "## Portfolio totals",
        "",
        "| Lifecycle stage | Count |",
        "|---|---:|",
    ]
    for stage in LIFECYCLE_STAGES:
        lines.append(f"| `{stage}` | {stages.get(stage, 0)} |")
    lines.extend(
        [
            "",
            f"Program state totals: active {states.get('active', 0)}; waiting {states.get('waiting', 0)}; complete {states.get('complete', 0)}.",
            "",
            "## Repository inventory",
            "",
            "| # | Repository | Type | HEAD | Stage | Evidence | Blocker | Next task | Dependencies | State |",
            "|---:|---|---|---|---|---|---|---|---|---|",
        ]
    )
    for index, repo in enumerate(repositories, 1):
        evidence_url = repo["evidence"][0]
        evidence = (
            f"[{_cell(repo['implementation_status'])}]({evidence_url})"
            f"; {_cell(repo['test_status'])}"
        )
        blocker = repo["blockers"][0] if repo["blockers"] else "None"
        dependencies = ", ".join(f"`{item}`" for item in repo["dependencies"]) or "—"
        lines.append(
            "| "
            + " | ".join(
                [
                    str(index),
                    f"[{repo['name']}]({repo['github_url']})",
                    _cell(repo["project_type"]),
                    f"`{repo['last_verified_head_sha'][:12]}`",
                    f"`{repo['lifecycle_stage']}`",
                    evidence,
                    _cell(blocker),
                    _cell(repo["next_task"]),
                    dependencies,
                    repo["program_state"],
                ]
            )
            + " |"
        )

    exp001 = experiment_by_id["EXP-001"]
    lines.extend(
        [
            "",
            "## Theory reconciliation",
            "",
            f"Concept coverage: {len(theory['concepts'])} canonical concepts; {len(current_concepts)} current concept repositories mapped exactly once; Agent Gearbox has no current repository.",
            "",
            "Canonical map: `program/THEORY_MAP.md`. Machine registry: `program/theory-registry.json`.",
            "",
            "## Highest-priority workstream",
            "",
            registry["current_highest_priority_workstream"],
            "",
            f"`EXP-001` — **{exp001['status']}** — {exp001['title']}",
            "",
            "Blockers: " + " ".join(exp001["blockers"]),
            "",
            "## Exact recommended next execution",
            "",
            registry["recommended_next_execution"],
            "",
            "## Mechanical source of truth",
            "",
            "- Registry: `program/registry.json`",
            "- Experiments: `program/experiments.json`",
            "- Theory registry: `program/theory-registry.json`",
            "- Theory map: `program/THEORY_MAP.md`",
            "- Lifecycle: `program/LIFECYCLE.md`",
            "- Operating rules: `program/OPERATING_RULES.md`",
            "- Priority rationale: `program/PRIORITY.md`",
            "- Integrity check: `python3 tools/validate_program.py`",
            "",
        ]
    )
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args(argv)
    registry = load_json(DEFAULT_REGISTRY)
    experiments = load_json(DEFAULT_EXPERIMENTS)
    try:
        content = render(registry, experiments)
    except ValueError as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        return 1
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != content:
            print(f"FAIL: {args.output} is stale; rerun tools/render_program_status.py", file=sys.stderr)
            return 1
        print(f"PASS: {args.output.name} matches the registry")
        return 0
    args.output.write_text(content, encoding="utf-8")
    print(f"Rendered {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
