#!/usr/bin/env python3
"""Render deterministic human views from the Opsle program registries."""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

from validate_program import (
    DEFAULT_EXPERIMENTS,
    DEFAULT_REGISTRY,
    DEFAULT_THEORY_MAP,
    DEFAULT_THEORY_REGISTRY,
    EXPECTED_REPOSITORIES,
    LIFECYCLE_STAGES,
    load_json,
    validate,
    validate_theory,
)

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "PROGRAM_STATUS.md"
DEFAULT_PRIORITY_OUTPUT = ROOT / "program" / "PRIORITY.md"


def _cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def _validate_for_render(registry: dict, experiments: dict) -> dict:
    errors = validate(registry, experiments)
    theory = load_json(DEFAULT_THEORY_REGISTRY)
    theory_map_text = DEFAULT_THEORY_MAP.read_text(encoding="utf-8")
    errors.extend(validate_theory(theory, registry, theory_map_text))
    if errors:
        raise ValueError("cannot render invalid registry: " + "; ".join(errors))
    return theory


def _priority_table_lines(control: dict) -> list[str]:
    lines = [
        "| Lane | Objective | Repositories | Entry gate |",
        "|---|---|---|---|",
    ]
    for lane in control["lanes"]:
        repositories = ", ".join(f"`{name}`" for name in lane["repositories"])
        lines.append(
            f"| **{lane['name']}** | {_cell(lane['objective'])} | "
            f"{repositories} | {_cell(lane['entry_condition'])} |"
        )
    return lines


def render_priority(registry: dict, experiments: dict) -> str:
    _validate_for_render(registry, experiments)
    control = registry["program_control"]
    admission = control["work_item_admission"]
    ds = control["durable_supervisor_v0_1"]
    tasks = control["opsle_tasks"]
    visible = registry["visible_value"]
    lines = [
        "# Evidence-driven program priority",
        "",
        "<!-- Generated by tools/render_program_status.py from program/registry.json. -->",
        "",
        "`program/registry.json` is the sole priority authority. Edit the registry, not this file.",
        "",
        "## Operating question",
        "",
        f"> {control['operating_question']}",
        "",
        "## Anti-nitpick guardrail",
        "",
        admission["rule"],
        "",
        "Normally admit new work only for:",
        "",
    ]
    lines.extend(f"- {reason}" for reason in admission["qualifying_reasons"])
    lines.extend(["", "Park by default:", ""])
    lines.extend(f"- {reason}" for reason in admission["parked_by_default"])
    lines.extend(["", "## NOW / NEXT / THEN / LATER / PARKED", ""])
    lines.extend(_priority_table_lines(control))
    for lane in control["lanes"]:
        lines.extend(
            [
                "",
                f"### {lane['name']} — {lane['objective']}",
                "",
                f"Entry: {lane['entry_condition']}",
                "",
                f"Exit: {lane['exit_condition']}",
            ]
        )

    lines.extend(
        [
            "",
            "## Durable Supervisor v0.1 stopping criteria",
            "",
            f"Status: **{ds['status']}**. Foundation: `{ds['durability_foundation']}`.",
            "",
            f"Verified main: `{ds['verified_main_sha']}`. Runtime: `{ds['verified_runtime_state']}` "
            f"as durably recorded at `{ds['runtime_state_recorded_at']}`.",
            "",
        ]
    )
    lines.extend(
        f"{index}. **{item['status']}** — {item['criterion']}"
        for index, item in enumerate(ds["stopping_criteria"], 1)
    )
    lines.extend(
        [
            "",
            "## Opsle Tasks boundary",
            "",
            f"{tasks['future_name']} is the {tasks['role']}. Its current repository remains "
            f"`{tasks['current_repository']}`.",
            "",
            "Measure: " + ", ".join(tasks["measurements"]) + ".",
            "",
            "Without separate authorization, do not:",
            "",
        ]
    )
    lines.extend(f"- {item}" for item in tasks["prohibited_without_separate_authorization"])
    lines.extend(["", "## Evidence-triggered concept activation", ""])
    lines.extend(
        f"- {item['deficiency']} → "
        + ", ".join(f"`{name}`" for name in item["repositories"])
        for item in control["concept_activation"]
    )
    lines.extend(
        [
            "",
            "## Visible Value target",
            "",
            f"Baseline: {visible['baseline']}",
            "",
            visible["baseline_rule"],
            "",
        ]
    )
    lines.extend(
        f"- **{item['name']}** — {item['definition']}"
        for item in visible["value_kinds"]
    )
    lines.extend(
        [
            "",
            "Per-child receipt: " + "; ".join(visible["per_child_receipt_fields"]) + ".",
            "",
            "Supervisor/run summary: "
            + "; ".join(visible["supervisor_summary_fields"])
            + ".",
            "",
            "## Later",
            "",
        ]
    )
    lines.extend(f"- {item}" for item in control["later_items"])
    lines.extend(["", "## Parked", ""])
    lines.extend(f"- {item}" for item in control["parked_items"])
    lines.extend(
        [
            "",
            "## Exact next execution",
            "",
            control["exact_next_execution"],
            "",
        ]
    )
    return "\n".join(lines)


def render(registry: dict, experiments: dict) -> str:
    theory = _validate_for_render(registry, experiments)
    repositories = registry["repositories"]
    control = registry["program_control"]
    ds = control["durable_supervisor_v0_1"]
    stages = Counter(repo["lifecycle_stage"] for repo in repositories)
    states = Counter(repo["program_state"] for repo in repositories)
    experiment_by_id = {item["id"]: item for item in experiments["experiments"]}
    current_concepts = [
        concept
        for concept in theory["concepts"]
        if concept["current_repository"] is not None
    ]
    satisfied = sum(
        item["status"] == "SATISFIED" for item in ds["stopping_criteria"]
    )
    lines = [
        "# Opsle program status",
        "",
        "<!-- Generated by tools/render_program_status.py from program/registry.json, "
        "program/experiments.json, program/theory-registry.json, and "
        "program/THEORY_MAP.md. -->",
        "",
        f"**Coverage: {len(repositories)}/{len(EXPECTED_REPOSITORIES)} expected repositories; duplicates: 0.**",
        "",
        f"Last verified: `{registry['last_verified_at']}`. HEADs are the verified default-branch revisions, not an assumption about later changes.",
        "",
        "## Program direction",
        "",
        f"> {control['operating_question']}",
        "",
        f"Current lane: **{control['current_lane']}**. Durable Supervisor v0.1: "
        f"**{ds['status']}** ({satisfied}/{len(ds['stopping_criteria'])} stopping criteria satisfied).",
        "",
        "Full generated priority view: `program/PRIORITY.md`.",
        "",
        "### Priority stack",
        "",
    ]
    lines.extend(_priority_table_lines(control))
    lines.extend(
        [
            "",
            "### Exact next execution",
            "",
            control["exact_next_execution"],
            "",
            "## Portfolio totals",
            "",
            "| Lifecycle stage | Count |",
            "|---|---:|",
        ]
    )
    for stage in LIFECYCLE_STAGES:
        lines.append(f"| `{stage}` | {stages.get(stage, 0)} |")
    lines.extend(
        [
            "",
            f"Program state totals: active {states.get('active', 0)}; waiting {states.get('waiting', 0)}; complete {states.get('complete', 0)}.",
            "",
            "## Repository inventory",
            "",
            "| # | Repository | Type | HEAD | Stage | Evidence | Blocker | Next task | Dependencies | State |",
            "|---:|---|---|---|---|---|---|---|---|---|",
        ]
    )
    for index, repo in enumerate(repositories, 1):
        evidence_url = repo["evidence"][0]
        evidence = (
            f"[{_cell(repo['implementation_status'])}]({evidence_url})"
            f"; {_cell(repo['test_status'])}"
        )
        blocker = repo["blockers"][0] if repo["blockers"] else "None"
        dependencies = ", ".join(f"`{item}`" for item in repo["dependencies"]) or "—"
        lines.append(
            "| "
            + " | ".join(
                [
                    str(index),
                    f"[{repo['name']}]({repo['github_url']})",
                    _cell(repo["project_type"]),
                    f"`{repo['last_verified_head_sha'][:12]}`",
                    f"`{repo['lifecycle_stage']}`",
                    evidence,
                    _cell(blocker),
                    _cell(repo["next_task"]),
                    dependencies,
                    repo["program_state"],
                ]
            )
            + " |"
        )

    exp001 = experiment_by_id["EXP-001"]
    lines.extend(
        [
            "",
            "## Theory reconciliation",
            "",
            f"Concept coverage: {len(theory['concepts'])} canonical concepts; {len(current_concepts)} current concept repositories mapped exactly once; Agent Gearbox maps to opsle/gearbox.",
            "",
            "Canonical map: `program/THEORY_MAP.md`. Machine registry: `program/theory-registry.json`.",
            "",
            "## Experiment state",
            "",
            f"`EXP-001` — **{exp001['status']}** — {exp001['title']}",
            "",
            "Blockers: " + " ".join(exp001["blockers"]),
            "",
            "## Mechanical source of truth",
            "",
            "- Portfolio and priority authority: `program/registry.json`",
            "- Generated priority view: `program/PRIORITY.md`",
            "- Experiments: `program/experiments.json`",
            "- Theory registry: `program/theory-registry.json`",
            "- Theory map: `program/THEORY_MAP.md`",
            "- Lifecycle: `program/LIFECYCLE.md`",
            "- Operating rules: `program/OPERATING_RULES.md`",
            "- Integrity check: `python3 tools/validate_program.py`",
            "",
        ]
    )
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--priority-output", type=Path, default=DEFAULT_PRIORITY_OUTPUT
    )
    args = parser.parse_args(argv)
    registry = load_json(DEFAULT_REGISTRY)
    experiments = load_json(DEFAULT_EXPERIMENTS)
    try:
        content = render(registry, experiments)
        priority_content = render_priority(registry, experiments)
    except ValueError as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        return 1
    if args.check:
        stale = []
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != content:
            stale.append(str(args.output))
        if (
            not args.priority_output.exists()
            or args.priority_output.read_text(encoding="utf-8") != priority_content
        ):
            stale.append(str(args.priority_output))
        if stale:
            print(
                "FAIL: stale generated files: "
                + ", ".join(stale)
                + "; rerun tools/render_program_status.py",
                file=sys.stderr,
            )
            return 1
        print(
            f"PASS: {args.output.name} and {args.priority_output.name} match the registry"
        )
        return 0
    args.output.write_text(content, encoding="utf-8")
    args.priority_output.write_text(priority_content, encoding="utf-8")
    print(f"Rendered {args.output} and {args.priority_output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
