#!/usr/bin/env python3
"""Render deterministic human views from the Opsle program registries."""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

from validate_program import (
    DEFAULT_EXPERIMENTS,
    DEFAULT_REGISTRY,
    DEFAULT_THEORY_MAP,
    DEFAULT_THEORY_REGISTRY,
    _canonical_json_sha256,
    LIFECYCLE_STAGES,
    load_json,
    validate,
    validate_theory,
)

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "PROGRAM_STATUS.md"
DEFAULT_PRIORITY_OUTPUT = ROOT / "program" / "PRIORITY.md"


def _cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def _validate_for_render(registry: dict, experiments: dict) -> dict:
    errors = validate(registry, experiments)
    theory = load_json(DEFAULT_THEORY_REGISTRY)
    theory_map_text = render_theory_map(theory, registry)
    errors.extend(validate_theory(theory, registry, theory_map_text))
    if errors:
        raise ValueError("cannot render invalid registry: " + "; ".join(errors))
    return theory


def _priority_table_lines(control: dict) -> list[str]:
    lines = [
        "| Lane | Objective | Repositories | Entry gate |",
        "|---|---|---|---|",
    ]
    for lane in control["lanes"]:
        repositories = ", ".join(f"`{name}`" for name in lane["repositories"])
        lines.append(
            f"| **{lane['name']}** | {_cell(lane['objective'])} | "
            f"{repositories} | {_cell(lane['entry_condition'])} |"
        )
    return lines


def render_priority(registry: dict, experiments: dict) -> str:
    _validate_for_render(registry, experiments)
    control = registry["program_control"]
    admission = control["work_item_admission"]
    tasks = control["opsle_tasks"]
    visible = registry["visible_value"]
    lines = [
        "# Evidence-driven program priority",
        "",
        "<!-- Generated by tools/render_program_status.py from program/registry.json. -->",
        "",
        "`program/registry.json` records research priorities. Opsle Tasks is the current workload and task-management authority. Edit the registry, not this generated view.",
        "",
        "## Operating question",
        "",
        f"> {control['operating_question']}",
        "",
        "## Anti-nitpick guardrail",
        "",
        admission["rule"],
        "",
        "Normally admit new work only for:",
        "",
    ]
    lines.extend(f"- {reason}" for reason in admission["qualifying_reasons"])
    lines.extend(["", "Park by default:", ""])
    lines.extend(f"- {reason}" for reason in admission["parked_by_default"])
    lines.extend(["", "## NOW / NEXT / THEN / LATER / PARKED", ""])
    lines.extend(_priority_table_lines(control))
    for lane in control["lanes"]:
        lines.extend(
            [
                "",
                f"### {lane['name']} — {lane['objective']}",
                "",
                f"Entry: {lane['entry_condition']}",
                "",
                f"Exit: {lane['exit_condition']}",
            ]
        )

    lines.extend(
        [
            "",
            "## Opsle Tasks boundary",
            "",
            f"{tasks['name']} is the {tasks['role']}. Its repository is "
            f"`{tasks['current_repository']}`.",
            "",
            "Measure: " + ", ".join(tasks["measurements"]) + ".",
            "",
            "Without separate authorization, do not:",
            "",
        ]
    )
    lines.extend(f"- {item}" for item in tasks["prohibited_without_separate_authorization"])
    lines.extend(["", "## Evidence-triggered concept activation", ""])
    lines.extend(
        f"- {item['deficiency']} → "
        + ", ".join(f"`{name}`" for name in item["repositories"])
        for item in control["concept_activation"]
    )
    lines.extend(
        [
            "",
            "## Visible Value target",
            "",
            f"Baseline: {visible['baseline']}",
            "",
            visible["baseline_rule"],
            "",
        ]
    )
    lines.extend(
        f"- **{item['name']}** — {item['definition']}"
        for item in visible["value_kinds"]
    )
    lines.extend(
        [
            "",
            "Per-child receipt: " + "; ".join(visible["per_child_receipt_fields"]) + ".",
            "",
            "Task/run summary: "
            + "; ".join(visible["run_summary_fields"])
            + ".",
            "",
            "## Later",
            "",
        ]
    )
    lines.extend(f"- {item}" for item in control["later_items"])
    lines.extend(["", "## Parked", ""])
    lines.extend(f"- {item}" for item in control["parked_items"])
    lines.extend(
        [
            "",
            "## Exact next execution",
            "",
            control["exact_next_execution"],
            "",
        ]
    )
    return "\n".join(lines)


def render(registry: dict, experiments: dict) -> str:
    theory = _validate_for_render(registry, experiments)
    repositories = registry["repositories"]
    control = registry["program_control"]
    stages = Counter(repo["lifecycle_stage"] for repo in repositories)
    states = Counter(repo["program_state"] for repo in repositories)
    experiment_by_id = {item["id"]: item for item in experiments["experiments"]}
    current_concepts = [
        concept
        for concept in theory["concepts"]
        if concept["current_repository"] is not None
    ]
    lines = [
        "# Opsle program status",
        "",
        "<!-- Generated by tools/render_program_status.py from program/registry.json, "
        "program/experiments.json, program/theory-registry.json, and "
        "program/THEORY_MAP.md. -->",
        "",
        f"**Coverage: {len(repositories)} recorded repositories; {registry['repository_counts']['current']} current, {registry['repository_counts']['historical']} historical; {registry['repository_counts']['workload_eligible']} workload eligible.**",
        "",
        f"Last verified: `{registry['last_verified_at']}`. HEADs are the verified default-branch revisions, not an assumption about later changes.",
        "",
        "## Program direction",
        "",
        f"> {control['operating_question']}",
        "",
        f"Current lane: **{control['current_lane']}**. Workload and task-management authority: **Opsle Tasks**.",
        "",
        "Full generated priority view: `program/PRIORITY.md`.",
        "",
        "### Priority stack",
        "",
    ]
    lines.extend(_priority_table_lines(control))
    lines.extend(
        [
            "",
            "### Exact next execution",
            "",
            control["exact_next_execution"],
            "",
            "## Highest evidenced research maturity (including historical sources)",
            "",
            "| Lifecycle stage | Count |",
            "|---|---:|",
        ]
    )
    for stage in LIFECYCLE_STAGES:
        lines.append(f"| `{stage}` | {stages.get(stage, 0)} |")
    lines.extend(
        [
            "",
            f"Program state totals: active {states.get('active', 0)}; waiting {states.get('waiting', 0)}; complete {states.get('complete', 0)}; historical {states.get('historical', 0)}.",
            "",
            "## Repository inventory",
            "",
            "| # | Repository | Type | HEAD | Stage | Evidence | Blocker | Next task | Dependencies | State / disposition |",
            "|---:|---|---|---|---|---|---|---|---|---|",
        ]
    )
    for index, repo in enumerate(repositories, 1):
        evidence_url = repo["evidence"][0]
        evidence = (
            f"[{_cell(repo['implementation_status'])}]({evidence_url})"
            f"; {_cell(repo['test_status'])}"
        )
        blocker = repo["blockers"][0] if repo["blockers"] else "None"
        dependencies = ", ".join(f"`{item}`" for item in repo["dependencies"]) or "—"
        lines.append(
            "| "
            + " | ".join(
                [
                    str(index),
                    f"[{repo['name']}]({repo['github_url']})",
                    _cell(repo["project_type"]),
                    f"`{repo['last_verified_head_sha'][:12]}`",
                    f"`{repo['lifecycle_stage']}`",
                    evidence,
                    _cell(blocker),
                    _cell(repo["next_task"]),
                    dependencies,
                    repo["program_state"] + " / " + repo["repository_disposition"] + (" → " + repo["consolidated_into"] if repo["consolidated_into"] else ""),
                ]
            )
            + " |"
        )

    lines.extend(["", "## Completed integration and retirement work", ""])
    for item in registry["completed_work"]:
        lines.append(f"- **{item['id']} — {item['status']}**: {item['scope']} " + ", ".join(f"[evidence {i}]({ref})" for i, ref in enumerate(item["evidence"], 1)))
    lines.extend(["", "Graphify is an optional standalone CLI, not an Opsle Tasks capability. Historical capability acceptance is superseded.", "", "Historical source evidence and superseded controls: `program/history/pre-consolidation/`. Retirement is not research completion."])
    exp001 = experiment_by_id["EXP-001"]
    lines.extend(
        [
            "",
            "## Theory reconciliation",
            "",
            f"Concept coverage: {len(theory['concepts'])} canonical concepts; {len(current_concepts)} live concepts sharing {theory['current_concept_repository_count']} current homes; Agent Gearbox maps to opsle/gearbox.",
            "",
            "Canonical map: `program/THEORY_MAP.md`. Machine registry: `program/theory-registry.json`.",
            "",
            "## Experiment state",
            "",
            f"`EXP-001` — **{exp001['status']}** — {exp001['title']}",
            "",
            "Blockers: " + " ".join(exp001["blockers"]),
            "",
            "## Mechanical source of truth",
            "",
            "- Research portfolio and priority evidence: `program/registry.json`",
            "- Workload and task-management authority: Opsle Tasks (`opsle/tasks`)",
            "- Generated priority view: `program/PRIORITY.md`",
            "- Experiments: `program/experiments.json`",
            "- Theory registry: `program/theory-registry.json`",
            "- Theory map: `program/THEORY_MAP.md`",
            "- Lifecycle: `program/LIFECYCLE.md`",
            "- Operating rules: `program/OPERATING_RULES.md`",
            "- Integrity check: `python3 tools/validate_program.py`",
            "",
        ]
    )
    lines.extend(["", "### All recorded experiments", "", "| Experiment | Status | Verdict |", "|---|---|---|"])
    for experiment in experiments["experiments"]:
        lines.append(f"| `{experiment['id']}` | {experiment['status']} | {_cell(experiment['verdict'])} |")
    lines.append("")
    return "\n".join(lines)


def render_theory_map(theory: dict, registry: dict) -> str:
    lines = [
        "# Current theory map", "",
        "<!-- Generated by tools/render_program_status.py. -->", "",
        "Opsle Tasks owns current workload and task management. The program ledger records research state; it does not create a parallel task queue.", "",
        "Gearbox determines where bounded work executes; Context Firewall determines what evidence returns. Visible Value validates receipts and presents operator measurements. Affected Verification plans checks under explicit evidence boundaries.", "",
        "Task 15 completed the versioned capability contract: trusted manifests, operator grants, immutable repository selection, lifecycle hooks, receipts and an execution-scoped model gateway. Graphify is an optional standalone CLI, not a Tasks capability.", "",
        "The final consolidation receipt supersedes earlier partial observations. Durable Supervisor is retired, with no current home or activation gate. Other consolidated concepts share Tasks or Gearbox; their source maturity does not increase through migration. `.github` remains a repository but is ineligible for workload execution.", "",
        "Historical definitions, extraction analysis, initial SHAs, licenses, negative evidence and superseded recommendations are preserved in [the historical map](history/pre-consolidation/THEORY_MAP.md) and [historical registry](history/pre-consolidation/theory-registry.json). They authorize no work.", "",
        f"Coverage: {theory['concept_count']} concepts; " + "; ".join(f"{key.lower()} {value}" for key, value in theory["concept_counts"].items()) + f"; {theory['current_concept_repository_count']} distinct current homes.", "",
        "Theory registry canonical SHA-256:", f"`{_canonical_json_sha256(theory)}`.", "",
        "| Concept identity | Classification | Executed / retained disposition | Confidence | Current home and maturity |",
        "|---|---|---|---|---|",
    ]
    for concept in theory["concepts"]:
        home = concept["current_repository"] or "none (retired)"
        lines.append(f"| `{concept['id']}` | `{concept['primary_classification']}` | `{concept['recommended_disposition']}` | `{concept['confidence']}` | {home}; {concept['highest_evidenced_stage']} |")
    lines.extend(["", "## Evidence limits", "",
        "Context Firewall remains PROTOTYPED: flat TAP plus Node spec/dot reporters and a semantic-only projection. Canonical packet metrics are audit measurements; downstream delivery is measured separately. This is not an arbitrary-log parser or production security boundary.", "",
        "Gearbox remains PROTOTYPED with provider-free bounded execution and deterministic phase routing. Routing Policy is consolidated into its documented contract. Capability integration does not prove comparative savings.", "",
        "Visible Value is PROTOTYPED: an independent validator and reporting CLI. It does not authenticate external producer evidence. Missing measurements remain absent and incompatible totals are excluded.", "",
        "Affected Verification remains VERIFIED, with research limited to OBSERVE/SHADOW. AV-EXP-002 remains FAIL; AV-EXP-003 repaired its known skip without establishing general selector completeness. Tasks may use bounded manifest-backed selection only with complete impact, catalog and check-boundary evidence; unknown evidence broadens or stops. This is not a general TRUSTED_BOUNDED promotion.", "",
        "EXP-001 remains PLANNED and unconsumed. Remote Incus execution proofs are operational observations; Task 15 implementation and repository consolidation do not complete research or establish token, cost, correctness or causal savings.", "",
        "Revision-linked completed work and verified inventory: [PROGRAM_STATUS](../PROGRAM_STATUS.md), [evidence](evidence/post-consolidation/README.md).", ""])
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--priority-output", type=Path, default=DEFAULT_PRIORITY_OUTPUT
    )
    args = parser.parse_args(argv)
    registry = load_json(DEFAULT_REGISTRY)
    experiments = load_json(DEFAULT_EXPERIMENTS)
    theory_content = render_theory_map(load_json(DEFAULT_THEORY_REGISTRY), registry)
    try:
        content = render(registry, experiments)
        priority_content = render_priority(registry, experiments)
    except ValueError as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        return 1
    if args.check:
        stale = []
        if not DEFAULT_THEORY_MAP.exists() or DEFAULT_THEORY_MAP.read_text(encoding="utf-8") != theory_content:
            stale.append(str(DEFAULT_THEORY_MAP))
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != content:
            stale.append(str(args.output))
        if (
            not args.priority_output.exists()
            or args.priority_output.read_text(encoding="utf-8") != priority_content
        ):
            stale.append(str(args.priority_output))
        if stale:
            print(
                "FAIL: stale generated files: "
                + ", ".join(stale)
                + "; rerun tools/render_program_status.py",
                file=sys.stderr,
            )
            return 1
        print(
            f"PASS: {args.output.name}, {args.priority_output.name}, and {DEFAULT_THEORY_MAP.name} match the registry"
        )
        return 0
    DEFAULT_THEORY_MAP.write_text(theory_content, encoding="utf-8")
    args.output.write_text(content, encoding="utf-8")
    args.priority_output.write_text(priority_content, encoding="utf-8")
    print(f"Rendered {args.output}, {args.priority_output}, and {DEFAULT_THEORY_MAP}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
